config/routes.rb
Rails.application.routes.draw do
  resources :books do
    collection do
      get :autocomplete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
require 'csv'

class Book < ApplicationRecord
  searchkick

  validates :title, presence: true
  validates :author, presence: true
  validates :publisher, presence: true
  validates :category, presence: true
  validates :published_on, presence: true

  composed_of :unit_cost,
              :class_name => 'Money',
              :mapping => [%w(unit_cost fractional), %w(currency currency_as_string)],
              :constructor => Proc.new { |unit_cost, currency| Money.new(unit_cost, currency || Money.default_currency) },
              :converter => Proc.new { |value| value.respond_to?(:to_money) ? (value.to_f.to_money rescue Money.empty) : Money.empty }

  CSV_FILE = File.join( Rails.root.to_s, 'db', "import", "books.csv")

  def price
    unit_cost.to_d * ( 1 + MARKUP[self.category] )
  end

  def display_price
    price.to_s
  end

  def self.import_csv(file)
    begin
      CSV.foreach(CSV_FILE, { headers: true, header_converters: :symbol }) do |row|
        book = Book.find_or_initialize_by(title: row[:title], author: row[:author], publisher: row[:publisher], category: row[:category], published_on: row[:published_on])
        book.attributes = row.to_hash.merge({:currency => "USD"})
        book.unit_cost = row[:unit_cost].to_f * 100.0
        book.save!
      end
    rescue Exception => e
      puts e.message
      puts "Book could not be created"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    query = params[:query].presence || '*'
    @books = Book.search(query)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def autocomplete
    render json ['test']
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :publisher, :published_on, :unit_cost, :category, :currency)
    end

  private

  def init_search_sort
    if params[:sort].to_s.start_with?("title")
      title_direction = params[:sort].to_s.split("!").first
      title_direction.slice!("title_")
      params[:search][:sort] = {}
      params[:search][:sort][:title] = title_direction
    end
    if params[:sort].to_s.start_with?("author")
      author_direction = params[:sort].to_s.split("!").first
      author_direction.slice!("author_")
      params[:search][:sort] = {}
      params[:search][:sort][:author] = author_direction
    end
    if params[:sort].to_s.start_with?("unit_cost")
      price_direction = params[:sort].to_s.split("!").first
      price_direction.slice!("unit_cost_")
      params[:search][:sort] = {}
      params[:search][:sort][:price] = price_direction
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :published_on %>
    <%= form.text_field :published_on %>
  </div>

  <div class="field">
    <%= form.label :unit_cost %>
    <%= form.text_field :unit_cost, value: book.unit_cost %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<%= form_tag books_path, method: :get do %>
  <p>
    <%= text_field_tag "query", params[:query], placeholder: 'Search' %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<p><%= will_paginate @books %></p>

<table id="table" class="parse">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Published on</th>
      <th>Price</th>
      <th>Category</th>
      <th>Currency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr class="tablerow" data-url="<%= book_path(book) %>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.published_on %></td>
        <td><%= book.unit_cost %></td>
        <td><%= book.category %></td>
        <td><%= book.currency %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

<%= javascript_pack_tag 'books' %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @book.published_on %>
</p>

<p>
  <strong>Unit cost:</strong>
  <%= @book.unit_cost %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @book.currency %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caplinkedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>